Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')

config_head = Split('''
os.h
os_cfg.h
os_cfg_app.h
''')

src = src + config_head

CPPPATH = [cwd]

group = DefineGroup('uCOS-III', src, depend = ['PKG_USING_UCOSIII_WRAPPER'], CPPPATH = CPPPATH)

Return('group')
