Import('rtconfig')
import os
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('uC-CPU', src, depend = ['PKG_USING_UCOSIII_WRAPPER'], CPPPATH = CPPPATH)

Return('group')
